version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  # These dependencies are skipped because they require a newer version of go:
  - dependency-name: "golang.org/x/sys"
  - dependency-name: "golang.org/x/text"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
